# Generated by Django 4.0 on 2022-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=500)),
                ('cityDescription', models.CharField(max_length=500)),
                ('cityImage1', models.CharField(max_length=500)),
                ('cityImage2', models.CharField(max_length=500)),
                ('cityImage3', models.CharField(max_length=500)),
                ('cityImage4', models.CharField(max_length=500)),
                ('cityImage5', models.CharField(max_length=500)),
                ('hospitalName', models.CharField(max_length=500)),
                ('hospitalContact', models.CharField(max_length=500)),
                ('hospitalLocation', models.CharField(max_length=500)),
                ('hospitalRating', models.CharField(max_length=500)),
                ('securityRating', models.CharField(max_length=500)),
                ('securityContact', models.CharField(max_length=500)),
                ('hotelLink', models.CharField(max_length=500)),
                ('hotelImage', models.CharField(max_length=500)),
                ('restaurantName', models.CharField(max_length=500)),
                ('restaurantLocation', models.CharField(max_length=500)),
                ('restaurantLink', models.CharField(max_length=500)),
                ('restaurantRating', models.CharField(max_length=500)),
                ('restaurantImg', models.CharField(max_length=500)),
                ('visaDescription', models.CharField(max_length=500)),
                ('visaLink', models.CharField(max_length=500)),
                ('visaImg', models.CharField(max_length=500)),
                ('tour1name', models.CharField(max_length=500)),
                ('tour1Description', models.CharField(max_length=500)),
                ('Tour1Img', models.CharField(max_length=500)),
                ('tour2name', models.CharField(max_length=500)),
                ('tour2Description', models.CharField(max_length=500)),
                ('tour3name', models.CharField(max_length=500)),
                ('tour3Description', models.CharField(max_length=500)),
                ('Tour3Img', models.CharField(max_length=500)),
            ],
        ),
    ]
